Repository nugraph/pynuml, pull requests merged in 2023-11, with the labels that each got.

#68 check for integral outliers
  pynuml/process/hitgraph.py
Labels: bug, processing

#66 Add multiple scattering to the standard labeler
  pynuml/labels/standard.py
Labels: labelling

#69 fix Delaunay edge processing
  pynuml/process/hitgraph.py
Labels: bug, processing

#70 bump to v23.11.dev
  pynuml/__init__.py
  pynuml/meta.yaml
Labels: release
