Repository nugraph/pynuml, pull requests merged in 2023-09, with the labels that each got.

#54 label charged tau as HIP
  pynuml/labels/standard.py
Labels: labelling

#55 switch to nu_vtx_corr
  pynuml/process/hitgraph.py
Labels: labelling

#56 update to v23.9.0
  pynuml/__init__.py
  pynuml/process/hitgraph.py
Labels: release

#57 safeguard event table access
  pynuml/process/hitgraph.py
Labels: bug

#58 add proton decay event labelling
  pynuml/labels/__init__.py
  pynuml/labels/pdk.py
Labels: labelling

#60 add metadata file for conda package
  meta.yaml
Labels: enhancement

#61 add D meson labelling
  pynuml/labels/standard.py
Labels: enhancement, labelling

#63 update documentation to use mamba command
  .gitignore
  README.md
  docs/install/installation.rst
Labels: documentation
